config/routes.rb
Honoluluanswers::Application.routes.draw do
  get "smsrequesthandler/smshandler"

  get "welcome/index"

  root :to => "home#index"

  # Content management
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :sessions => "sessions" }

  match '/about' => "home#about" , :as => :about
  match '/search/' => "search#index" , :as => :search, :via => [:get, :post]

  resources :categories, :only => :show

  # legacy, redirects to the appropriate specific resource
  resources :articles, :only => [:show, :article_type]

  resources :quick_answers, :only => :show
  resources :web_services, :only => :show
  resources :guides, :only => :show
  match '/articles/article-type/:content_type' => "articles#article_type"
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  include RailsNlp

  before_filter :filter_long_or_empty

  def index
    query = params[:q].strip

    @query = query

    @query_corrected = QueryExpansion.spell_check(query)

    query_expanded = QueryExpansion.expand(query)
    @query_expanded = query_expanded

    @results = Article.search(query_expanded).select(&:published?)


    respond_to do |format|
      format.json  { render @results }
      format.html
    end

  end

  private

  # Searchify can't handle requests longer than this (because of query
  # expansion + Tanker inefficencies.  >10 can result in >8000 byte request
  # strings)
  def filter_long_or_empty
    if params[:q].split.size > 10 || params[:q].blank?
      @query = params[:q]
      @results = []
      render and return
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<% set_meta_tags :description => "Search results for #{@query}.", :canonical => "http://answers.honolulu.gov#{request.fullpath}", :title => "Search results for #{@query}." %>

<div class="page-container search">
  <div class="row">
    <div class="span9">
      <div class="main-content">
        <div class="header">
          <h1>Search results for: &ldquo;<strong><%=@query%></strong>&rdquo;</h1>

          <% unless (@query_corrected == @query) || (@query_corrected.blank?) %>
            <div class="suggestion">
              Did you mean:"
              <%= link_to @query_corrected, search_path(:q => @query_corrected) %>
              "?
           </div>
          <% end %>

          <br/>
          <% if @results.blank? %>
            <p>
              Sorry, no results found for "<%=@query%>". Please try rephrasing
              your search terms.
            </p>
          <% else %>
            <ul>
              <% @results.each do |article| %>
                  <li class="article-listing">
                    <h2>
                      <%= link_to article.title, article_path(article.id) %>
                    </h2>
                    <p class="preview"><%= article.preview %></p>
                  </li>
                <% end %>
            </ul>
          <% end -%>

        </div>
      </div>
    </div>
    <div class="span3">
      <%= render :partial => 'shared/categories_sidebar' %>
    </div><!-- /span3 -->
  </div>
</div>